//Character Sheet JSON
//Sergey recommends breaking this down into little objects and passing them into the main constructor - Implement after identifying all other structures, break this down 
var character = { 
	"Name":"String",
	"Class":"String",
	"Level":0,
	"Background":"String",
	"PlayerName":"String",
	"Alignment":"String",
	"Exp":0,
	"AbilityScores":{
		"Str":0,
		"Dex":0,
		"Con":0,
		"Int":0,
		"Wis":0,
		"Cha":0
	},
	"SavingThrows":{
		"Str":0,
		"Dex":0,
		"Con":0,
		"Int":0,
		"Wis":0,
		"Cha":0
	},
	"Skills":{
		"Acrobatics":{
			"Proficient":false,
			"Rank":0
		},
		"AnimalHandling":{
			"Proficient":false,
			"Rank":0
		},
		"Arcana":{
			"Proficient":false,
			"Rank":0
		},
		"Athletics":{
			"Proficient":false,
			"Rank":0
		},
		"Deception":{
			"Proficient":false,
			"Rank":0
		},
		"History":{
			"Proficient":false,
			"Rank":0
		},
		"Insight":{
			"Proficient":false,
			"Rank":0
		},
		"Intimidation":{
			"Proficient":false,
			"Rank":0
		},
		"Investigation":{
			"Proficient":false,
			"Rank":0
		},
		"Medicine":{
			"Proficient":false,
			"Rank":0
		},
		"Nature":{
			"Proficient":false,
			"Rank":0
		},
		"Perception":{
			"Proficient":false,
			"Rank":0
		},
		"Performance":{
			"Proficient":false,
			"Rank":0
		},
		"Persuasion":{
			"Proficient":false,
			"Rank":0
		},
		"Religion":{
			"Proficient":false,
			"Rank":0
		},
		"SelightOfHand":{
			"Proficient":false,
			"Rank":0
		},
		"Stealth":{
			"Proficient":false,
			"Rank":0
		},
		"Survival":{
			"Proficient":false,
			"Rank":0
		}
	},
	"Passive Perception":0,
	"ProficiencyBonus":0,
	"ArmorClass":0,
	"Initiative":0,
	"Speed":0,
	"HitPoints":0,
	"TempHP":0,
	"HitDice": {
		"1d4":0,
		"1d6":0,
		"1d8":0,
		"1d10":0,
		"1d12":0
	},
	"PersonalityTraits":"String",
	"Ideals":"String",
	"Bonds":"String",
	"Flaws":"String",
	"DeathSaves":{
		"Successes":0,
		"Failures":0
	},
	"Traits":{

	},
	"AttacksAndSpellcasting":{
		"Weapons":{
			"Weapon":{
				"Name":"weapon",
				"DamageDie":{
					"1d4":0,
					"1d6":0,
					"1d8":0,
					"1d10":0,
					"1d12":0
				},
				"DamageType":{
					"Slashing":false,
					"Bludgeoning":false,
					"Piercing":false
				},
				"AttackBonus":0
			},
		},
	},
	"Equipment":{

	},
	"Money":{
		"Copper":0,
		"Silver":0,
		"Electrum":0, 
		"Gold":0,
		"Platinum":0
	},
	"Features":{

	},
	"Age":0,
	"Height":{
		"Feet":0,
		"Inches":0
	},
	"Weight":0,
	"Eyes":"None",
	"Skin":"Some",
	"Hair":"Plenty",
	"Treasure":{

	},
	"SpellCasting":{
		"SpellCastingAbility":{

			"Str":false,
			"Dex":false,
			"Con":false,
			"Int":false,
			"Wis":false,
			"Cha":false
		},
		"SpellSaveDC":0,
		"SpellAttackBonus":0,
		"SpellLevels":{
		"Cantrips":{
			"MageHand":{
				"SpellName":"Name",
				"SpellRequirements":{
					"Requirements":{
						"Visual":false,
						"Somatic":false,
						"...":false // More to add here
					}
					"Component1":"Something"
				},
				"Damage":{
					"1d4":0,
					"1d6":0,
					"1d8":0,
					"1d10":0,
					"1d12":0
				},
				"Range":0,
				"Duration":0
				},
			},
		"SpellLevel1":{
			},
		"SpellLevel2":{
			},
		"SpellLevel3":{
			},
		"SpellLevel4":{
			},
		"SpellLevel5":{
			},
		"SpellLevel6":{
			},
		"SpellLevel7":{
			},			
		"SpellLevel8":{
			},
		"SpellLevel9":{
			}	
		},
	},
}